test: ../../../fdaPDE/src/multithreading/worker_queue.h ../../../fdaPDE/src/multithreading/header_check.h
	g++ -std=c++20 -pthread -I../../../ -o test_deque_vs_worker_queue test_deque_vs_worker_queue.cpp
	g++ -std=c++20 -pthread -I../../../ -o test_pop_push_multithread test_pop_push_multithread.cpp
	g++ -std=c++20 -pthread -I../../../ -o test_pop_push test_pop_push.cpp
	g++ -std=c++20 -pthread -I../../../ -o toy_threadpool toy_threadpool.cpp      